name: build bombsquad-x86

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - main
    paths:
      - ./Images/X86/**
      
jobs:
  push:
    name: "bombsquad-x86"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: ./Images/X86
          file: ./Images/X86/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            viruslauncher/bombsquad:x86
